const BARS = ['▁', '▂', '▃', '▄', '▅', '▆', '▇', '█'];

export function sparkline(values: readonly number[]): string {
  if (values.length === 0) return '—';
  const max = Math.max(...values, 1);
  return values
    .map((v) => BARS[Math.min(7, Math.round((v / max) * 7))])
    .join('');
}

export function formatDeltaCell({ thisWeek, lastWeek }: { thisWeek: number; lastWeek: number }): string {
  const diff = thisWeek - lastWeek;
  const sign = diff >= 0 ? '+' : '';
  if (lastWeek === 0) {
    return diff > 0 ? `${sign}${diff} (new)` : '—';
  }
  const pct = Math.round(((thisWeek - lastWeek) / lastWeek) * 100);
  const pctSign = pct >= 0 ? '+' : '';
  return `${sign}${diff} (${pctSign}${pct}%)`;
}

export interface ReportRow {
  metric: string;
  thisWeek: number | null;
  lastWeek: number | null;
  unavailable?: string;
  weeks: readonly number[];  // 4 most recent buckets
}

export interface ReportSection {
  name: string;
  rows: ReportRow[];
}

export function renderReport(sections: ReportSection[], date: string): string {
  const lines: string[] = [];
  lines.push(`# GTM weekly snapshot — ${date}`);
  lines.push('');
  lines.push('> Generated by `nx run posthog-tools:report`. Notes below are hand-edited.');
  lines.push('> Counts cover completed UTC days ending yesterday; today’s partial bucket is excluded. The sparkline shows four consecutive 7-day periods.');
  lines.push('');
  for (const section of sections) {
    lines.push(`## ${section.name}`);
    lines.push('');
    lines.push('| Metric | Last 7 complete UTC days | Preceding 7 UTC days | Δ | 4 periods |');
    lines.push('|--------|----------:|----------:|--:|------|');
    for (const row of section.rows) {
      if (row.thisWeek === null || row.lastWeek === null) {
        lines.push(`| ${row.metric} | Unavailable: ${row.unavailable ?? 'no complete result'} | — | — | — |`);
        continue;
      }
      lines.push(
        `| ${row.metric} | ${row.thisWeek.toLocaleString()} | ${row.lastWeek.toLocaleString()} | ${formatDeltaCell({ thisWeek: row.thisWeek, lastWeek: row.lastWeek })} | ${sparkline(row.weeks)} |`,
      );
    }
    lines.push('');
  }
  lines.push('## Notes');
  lines.push('');
  lines.push('<!-- HUMAN: edit this section before merging the PR. Three bullets max. -->');
  lines.push('- _Add observations here before merging._');
  lines.push('');
  return lines.join('\n');
}

import { writeFile, mkdir, access, readFile, readdir } from 'node:fs/promises';
import { join, resolve as resolvePath, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ph } from './client.js';
import { fetchAllPages } from './sync.js';
import { DashboardLocal } from './schema.js';

interface FetchedInsight {
  id: number;
  name: string;
  filters?: { insight?: string };
  query?: any;
  result?: any;
}

interface FetchedDashboard {
  id: number;
  name: string;
  tags?: string[];
  tiles?: Array<{ insight?: number | { id: number } }>;
}

/** Daily total-event series are additive. Unique actors and funnels are not. */
export function insightReportRows(insight: FetchedInsight, asOf = new Date()): ReportRow[] {
  const unavailable = (reason: string): ReportRow[] => [{ metric: insight.name, thisWeek: null, lastWeek: null, weeks: [], unavailable: reason }];
  const source = insight.query?.kind === 'TrendsQuery' ? insight.query : insight.query?.source;
  if (source?.kind !== 'TrendsQuery') return unavailable('unsupported insight type (funnels and retention require separate interpretation)');
  if (source.interval !== 'day') return unavailable('requires daily event totals');
  if (!Array.isArray(source.series) || !source.series.length) return unavailable('missing series definition');
  if (source.series.some((series: any) => series.math && series.math !== 'total')) return unavailable('unique or non-additive series cannot be summed into weekly counts');
  if (source.breakdownFilter?.breakdown) return unavailable('breakdown results may be truncated; inspect the dashboard');
  const results = insight.result;
  if (!Array.isArray(results) || results.length !== source.series.length) return unavailable('missing or incomplete result series');
  if (results.some((series: any) => !Array.isArray(series.data) || series.data.length < 28 || series.data.some((value: unknown) => typeof value !== 'number' || !Number.isFinite(value) || value < 0))) return unavailable('missing complete 28-day numeric results');
  const dayMs = 86_400_000;
  const today = Date.UTC(asOf.getUTCFullYear(), asOf.getUTCMonth(), asOf.getUTCDate());
  if (!Number.isFinite(today)) return unavailable('invalid UTC report date');
  const expectedDays = Array.from({ length: 28 }, (_, index) => new Date(today - (28 - index) * dayMs).toISOString().slice(0, 10));
  const rows: ReportRow[] = [];
  for (const [index, series] of results.entries()) {
    if (!Array.isArray(series.days) || series.days.length !== series.data.length) return unavailable('missing or mismatched daily result dates');
    const byDay = new Map<string, number>();
    for (const [position, day] of series.days.entries()) {
      if (typeof day !== 'string' || !/^\d{4}-\d{2}-\d{2}$/u.test(day)) return unavailable('invalid or partial daily result dates');
      const timestamp = Date.parse(`${day}T00:00:00Z`);
      if (!Number.isFinite(timestamp) || new Date(timestamp).toISOString().slice(0, 10) !== day || timestamp > today || byDay.has(day)) return unavailable('invalid or duplicate daily result dates');
      byDay.set(day, series.data[position]);
    }
    if (expectedDays.some(day => !byDay.has(day))) return unavailable('missing complete UTC 28-day window ending yesterday; cached data may be stale');
    // Extra older buckets and today's partial bucket do not enter the report.
    const data = expectedDays.map(day => byDay.get(day) as number);
    const weeks = Array.from({ length: 4 }, (_, week) => data.slice(week * 7, (week + 1) * 7).reduce((sum, value) => sum + value, 0));
    rows.push({ metric: results.length > 1 ? `${insight.name} — ${source.series[index].custom_name ?? series.label ?? source.series[index].name ?? `series ${index + 1}`}` : insight.name, thisWeek: weeks[3], lastWeek: weeks[2], weeks });
  }
  return rows;
}

// Throws on PostHog HTTP errors instead of silently returning empty results.
// A zero-row report is signal; a failed-auth empty report is misleading.
function expectOk<T>(r: { data?: T; error?: unknown }, op: string): T {
  if (r.error || r.data === undefined) {
    throw new Error(`PostHog ${op} failed: ${JSON.stringify(r.error)}`);
  }
  return r.data;
}

interface ReportClient {
  GET(path: string, options?: any): Promise<{ data?: unknown; error?: unknown }>;
  POST?(path: string, options?: any): Promise<{ data?: unknown; error?: unknown }>;
}

/**
 * Breakdown insights carry a `breakdown_limit`, so PostHog returns only the top N
 * values and summing the returned series would undercount. We re-run the same
 * trends query with the breakdown removed and label the row accordingly.
 */
export const BREAKDOWN_TOTAL_SUFFIX = ' — total across all breakdown values';

/** `blocking` recomputes a stale cache and returns only when the query is done. */
const REFRESH = 'blocking' as const;
const POLL_ATTEMPTS = 10;
const POLL_INTERVAL_MS = 3_000;

function trendsSource(insight: FetchedInsight): any {
  return insight.query?.kind === 'TrendsQuery' ? insight.query : insight.query?.source;
}

function stillComputing(insight: FetchedInsight | undefined): boolean {
  const status = (insight as any)?.query_status;
  return !Array.isArray(insight?.result) && !!status && status.complete !== true;
}

/**
 * `blocking` normally returns a computed result, but PostHog may hand back a
 * query_status instead. Poll the cache a bounded number of times rather than
 * hanging — an insight that never completes stays Unavailable, never zero.
 */
async function fetchInsight(c: ReportClient, id: number, sleep: (ms: number) => Promise<void>): Promise<FetchedInsight> {
  const get = async (refresh: string) =>
    expectOk(await c.GET('/insights/{id}/' as any, { params: { path: { id }, query: { refresh } } } as any) as any, `get insight ${id}`) as FetchedInsight;
  let insight = await get(REFRESH);
  for (let attempt = 0; attempt < POLL_ATTEMPTS && stillComputing(insight); attempt += 1) {
    await sleep(POLL_INTERVAL_MS);
    insight = await get('force_cache');
  }
  return insight;
}

/** Re-runs the insight's own trends query with the breakdown stripped. */
async function breakdownTotalRows(c: ReportClient, insight: FetchedInsight, source: any, asOf: Date): Promise<ReportRow[]> {
  if (typeof c.POST !== 'function') return insightReportRows(insight, asOf);
  const flat = { ...source };
  delete flat.breakdownFilter;
  const response = await c.POST('/query/' as any, { body: { query: flat, refresh: REFRESH } } as any);
  const payload = expectOk(response as any, `query insight ${insight.id} without breakdown`) as any;
  const result = Array.isArray(payload?.results) ? payload.results : payload?.result;
  return insightReportRows({ ...insight, name: `${insight.name}${BREAKDOWN_TOTAL_SUFFIX}`, query: flat, result }, asOf);
}

async function managedDashboardIds(): Promise<number[]> {
  const directory = join(dirname(fileURLToPath(import.meta.url)), 'dashboards');
  const ids: number[] = [];
  for (const file of (await readdir(directory)).filter(file => file.endsWith('.json')).sort()) {
    const dashboard = DashboardLocal.parse(JSON.parse(await readFile(join(directory, file), 'utf8')));
    if (dashboard.posthog_id === null) throw new Error(`Dashboard ${dashboard.slug} has not been synced`);
    ids.push(dashboard.posthog_id);
  }
  if (!ids.length) throw new Error('No managed dashboards configured');
  return ids;
}

export async function generateReport(options: { client?: ReportClient; asOf?: Date; dashboardIds?: readonly number[]; sleep?: (ms: number) => Promise<void> } = {}): Promise<{ markdown: string; date: string }> {
  const asOf = options.asOf ?? new Date();
  const c = options.client ?? ph();
  const ids = options.dashboardIds ?? await managedDashboardIds();
  const sleep = options.sleep ?? ((ms: number) => new Promise<void>(resolve => setTimeout(resolve, ms)));
  const dashboards = await fetchAllPages<FetchedDashboard>(async (offset, limit) => {
    const response = await c.GET('/dashboards/' as any, { params: { query: { limit, offset } } } as any);
    return expectOk(response, 'list dashboards') as { results: FetchedDashboard[]; next?: string | null };
  });

  const sections: ReportSection[] = [];
  for (const id of ids) {
    if (!dashboards.some(dashboard => dashboard.id === id)) throw new Error(`Managed dashboard ${id} is absent from PostHog`);
    const response = await c.GET('/dashboards/{id}/' as any, { params: { path: { id } } } as any);
    const d = expectOk(response, `get dashboard ${id}`) as FetchedDashboard;
    if (!Array.isArray(d.tiles)) throw new Error(`Dashboard ${id} response is missing tiles`);
    const rows: ReportRow[] = [];
    for (const tile of d.tiles) {
      const tileId = typeof tile.insight === 'number' ? tile.insight : tile.insight?.id;
      if (typeof tileId !== 'number') continue;
      const insight = await fetchInsight(c, tileId, sleep);
      const source = trendsSource(insight);
      if (source?.kind === 'TrendsQuery' && source.breakdownFilter?.breakdown) {
        rows.push(...await breakdownTotalRows(c, insight, source, asOf));
        continue;
      }
      rows.push(...insightReportRows(insight, asOf));
    }
    if (!rows.length) rows.push({ metric: d.name, thisWeek: null, lastWeek: null, weeks: [], unavailable: 'no insight tiles on this dashboard' });
    sections.push({ name: d.name, rows });
  }

  const date = asOf.toISOString().slice(0, 10);
  return { markdown: renderReport(sections, date), date };
}

async function nextOutputPath(reportsDir: string, date: string): Promise<string> {
  const base = join(reportsDir, `${date}-weekly`);
  let candidate = `${base}.md`;
  let suffix = 2;
  while (true) {
    try {
      await access(candidate);
      candidate = `${base}-${suffix}.md`;
      suffix += 1;
    } catch {
      return candidate;
    }
  }
}

async function main(): Promise<number> {
  let report: { markdown: string; date: string };
  try {
    report = await generateReport();
  } catch (err) {
    console.error(`Report generation failed: ${err instanceof Error ? err.message : err}`);
    return 1;
  }
  const here = dirname(fileURLToPath(import.meta.url));
  const reportsDir = resolvePath(here, '..', '..', 'docs', 'gtm', 'reports');
  await mkdir(reportsDir, { recursive: true });
  const outPath = await nextOutputPath(reportsDir, report.date);
  await writeFile(outPath, report.markdown, 'utf8');
  console.log(`Wrote ${outPath}`);
  return 0;
}

const isDirectRun = process.argv[1] && resolvePath(process.argv[1]) === fileURLToPath(import.meta.url);
if (isDirectRun) {
  main().then((code) => process.exit(code));
}
